### ISSUE TITLE
One Touch Verio IQ

### ISSUE THREAD

**Issue by fishforbreakfast** [Flameeyes/glucometerutils#30]
Hi,
Thank you for your work on this project.  I just received a One Touch Verio IQ a few days ago.  I did some investigating about using it with Linux since I really don't run any windows on any of my machines and have only some old ppc macs laying around that don't get a lot of use.  Most of them are running ppc linux anyway.

The Verio IQ has a Silicon Labs cp2103 USB to UART interface.  My dmesg output when the device is plugged in is as follows:
[44106.568020] usb 5-2: new full-speed USB device number 4 using uhci_hcd
[44106.722029] usb 5-2: New USB device found, idVendor=10c4, idProduct=85a7
[44106.722041] usb 5-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[44106.722047] usb 5-2: Product: CP2103 USB to UART Bridge Controller
[44106.722052] usb 5-2: Manufacturer: Silicon Labs
[44106.722056] usb 5-2: SerialNumber: TGKHQ0M9

I added the vendor and product ID to the cp210x.c file in my source tree so that the kernel would properly recognize the device and re-compiled my kernel.  The device is now properly recognized as a UART and a ttyUSB is in /dev (see below, also see attached patch).

[44106.568020] usb 5-2: new full-speed USB device number 4 using uhci_hcd
[44106.722029] usb 5-2: New USB device found, idVendor=10c4, idProduct=85a7
[44106.722041] usb 5-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[44106.722047] usb 5-2: Product: CP2103 USB to UART Bridge Controller
[44106.722052] usb 5-2: Manufacturer: Silicon Labs
[44106.722056] usb 5-2: SerialNumber: TGKHQ0M9
[44106.728181] cp210x 5-2:1.0: cp210x converter detected
[44106.728368] usb 5-2: cp210x converter now attached to ttyUSB1

stty reports 115200 BAUD and 8n1.  I have tried to talk to the device with minicom but with no results.  I also tried some of the serial commands from the other meters that you have listed without results as well.

Wondering if you have any hints or comments???

Regards,

Fred

[OneTouch-Verio_IQ.diff.txt](https://github.com/Flameeyes/glucometerutils/files/1503975/OneTouch-Verio_IQ.diff.txt)

**Comment by Flameeyes** [comment]
Hello! I don't have a Verio IQ myself although I think there's one coming my way at some point in the next few weeks

I would suggest you send the cp210x patch to the linux kernel mailing list, so that it can be supported by the driver there. But as for supporting it here, we'd have to figure out what the protocol is.

Since you don't have any Windows machine, that's going to be trickier. You could try and see if the driver for the otultramini reports anything at all, as that's one of the other serial protocols we know is supported.

**Comment by fishforbreakfast** [comment]
Thanks,
I will be sending the patch to the Linux kernel maintainers.  I'll also try some of the serial protocols that you have available.  I've already tried the sd-biosensor codes with no results.

Regards,

Fred

**Comment by Flameeyes** [comment]
Yeah the only one that *may* work, but unlikely, is the otultramini because it's the same company behind it. Everything else is not going to work, so no reason to spend time on it.

**Comment by fishforbreakfast** [comment]
OK,
I'll give it a try.

Take Care,

Fred

**Comment by fishforbreakfast** [comment]
I'm looking for the otultramini specs but can't find them in glucometer-protocols or glucometerutils ???

**Comment by Flameeyes** [comment]
Sorry I didn't realize I didn't reply to that comment.

The OTUltarMini specs are (or at least were) available online directly from lifescan, and as such I have not rewritten them in the other repository, as I have not reversed them, but just implemented.

Searching for "lifescan otultramini protocol" should be enough to find the PDF.

But since this piqued my interest, and I managed to find a place to order the meter from for cheap, so I may be able to help soonish.

**Comment by ngharo** [comment]
Funny, I just started investigating pulling measurements from a OneTouch Verio IQ device moments before your latest comment.  I also patched cp210x with the IQ VID:PID.

Patched VID:PID of the other OneTouch drivers to try talking the Verio IQ:
```
./glucometer.py --driver otultra2
... snip ...
  File "/home/nick/git/glucometerutils/glucometerutils/drivers/otultra2.py", line 90, in _validate_and_strip_checksum
    raise lifescan.MissingChecksum(line)
glucometerutils.support.lifescan.MissingChecksum: Response is missing checksum: 
```

```
./glucometer.py --driver otultraeasy
... snip ...
  File "/home/nick/git/glucometerutils/glucometerutils/drivers/otultraeasy.py", line 82, in read_from
    if self.cmd[_IDX_STX] != _STX:
IndexError: array index out of range
```

Let me know if you need any testing or other, maybe beer money :)

**Comment by Flameeyes** [comment]
Yeah I don't think there is much hope that the other drivers work at all with this model. This is the first model I know of that has a USB plug and a serial adapter on board (the Verio 2015 uses USB Mass Storage, the older Verio – which I have no access to – and the Ultra series use external USB-to-Serial adapters, and connect with a 3.5mm jack connector).

If you have a Windows computer or VM, and you're willing to set up some software for USB sniffing (there are a number of options), you can try downloading the data with the original software and post the USB chatter. That would be what I'm going to do.

(There's another trick, the OneTouch software used to (and probably still does) output all the debug information if open through WinDbg. Some of those debug messages tend to be very useful for reversing purposes.

**Comment by ngharo** [comment]
> Windows USB sniffing

I should be able to provide some dumps next week.

**Comment by Flameeyes** [comment]
In the meantime I have sent https://marc.info/?l=linux-usb&m=151454133823448 to linux-usb for merging. Once Johan merges it into mainline, I'll ask Greg to merge it for stable too (because this just makes my life easier).

**Comment by ngharo** [comment]
My associate was working on getting those dumps but we found that the OneTouch DMS software is no longer being distributed.  While looking around for a copy, I found that the Tidepool project supports the IQ.  

They're open source, check it out:
https://github.com/tidepool-org/chrome-uploader/blob/master/lib/drivers/onetouch/oneTouchVerioIQ.js

**Comment by Flameeyes** [comment]
Unfortunately the Tidepool project will not publish specs, so it still requires reverse engineering the code, but it's indeed at least easier. I got my device today so I should be able to start looking into it this weekend and see what I can do. From the code you linked it seems it's indeed an in-between the ultramini (I see link control referenced) and the verio2015 (commands prefixes with 0x4 instead of 0x5).

**Comment by Flameeyes** [comment]
Okay I copy-pasted and adapted code from the other two OneTouch drivers and I have something that may or may not work. In particular it seems like the TidePool driver does not include *any* validation of the constant bytes of the responses, which are actually used to report errors in the other protocols. It feels very strange.

If any of you feel like running it with `--vlog 4` and share with me the output (I expect it to error out) I'll try to poke it around a little more. Turns out I don't have the app installed right now on my usual laptop so I may not be able to take a trace from the actual software :(

**Comment by Flameeyes** [comment]
I managed to get a dump of the usb traffic from the software (found around) and it does not match at all...

In particular all the commands in the TidePool driver appears to use a 0x04 prefix (matches my Verio IQ reversing, differs from the 0x05 in the Ultra Easy), but the software here uses a 0x03 prefix.

And otherwise, everything else appears to be the same...

**Comment by Flameeyes** [comment]
This is even more interesting: it looks like the Verio 2015 responds to 0x03-prefixed commands just as well as 0x04 ones.

**Comment by Flameeyes** [comment]
But not 0x05.

**Comment by Flameeyes** [comment]
Okay the tidepool driver does not implement all the stuff that it needs to, so I'm particularly scared of it, but with a bit of snooping around I *should* have it working now, but it's still untested. In particular I don't know if it needs a special command to start the connection.

Please give it a try, just passing `--driver otverioiq` should be enough, as the device ID is well defined.

**Comment by fishforbreakfast** [comment]
Thanks!  I'll try it out.  Tonight isn't so good but tomorrow I will see 
what I can get out of my meter.

Thank you again & Regards,

Frederick

**Comment by Flameeyes** [comment]
Managed to test this with a custom kernel. And I'm surprised how far I went without testing it before :D 
I've now fixed the bugs I had around, and tested the zero log too, and it's all working. Yay!

By the way I posted some of my thoughts on all of this on my blog too: https://blog.flameeyes.eu/2018/01/diabetes-software-the-importance-of-documented-protocols/

**Comment by Flameeyes** [comment]
For the record, it looks like the cp210x patch is queued for all stable releases as of today, so it should be directly usable Really Soon Now™.
