### ISSUE TITLE
Export to Glucosio-format

### ISSUE THREAD

**Issue by Aeyoun** [Flameeyes/glucometerutils#4]
I’m using the [Glucosio](http://www.glucosio.org/) app. Would be useful to export from my meter via `glucometerutils` to a format Glucosio can import. (Currently, I’m typing in everything by hand.) The app got an export option in December with import still being marked as [in progress](https://github.com/Glucosio/glucosio-android/issues/158). Exporting to the app’s own format should be a safe bet:

    $ head -n4 glucosio.csv
    Concentration,Measured,Date,Time
    4.3mmol/L,2/1/16,08:08
    12.2mmol/L,2/1/16,01:30
    8.9mmol/L,1/31/16,22:24

Let the record show that I hate their stupid choice of timestamp format.

**Comment by Flameeyes** [comment]
Why is it using mmol/L? Sure it's the SI standard, but most devices would
use mg/dl internally. Also the header does not match the lines (4 column
rather than 3...) guess I need to bring it up with them and have them use a
sane format...

I have no problem with adding support for one more format, but it has less
definition than the one I'm using now..

On Tue, 16 Feb 2016, 00:04 Daniel Aleksandersen <notifications@github.com>
wrote:

> I’m using the Glucosio <http://www.glucosio.org/> app. Would be useful to
> export from my meter via glucometerutils to a format Glucosio can import.
> (Currently, I’m typing in everything by hand.) The app got an export option
> in December with import still being marked as in progress
> <https://github.com/Glucosio/glucosio-android/issues/158>. Exporting to
> the app’s own format should be a safe bet:
>
> $ head -n4 glucosio.csv
> Concentration,Measured,Date,Time
> 4.3mmol/L,2/1/16,08:08
> 12.2mmol/L,2/1/16,01:30
> 8.9mmol/L,1/31/16,22:24
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Flameeyes/glucometerutils/issues/4>.
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by Aeyoun** [comment]
Thanks, this way this util would have its first data-consumer/UI too. :)

But please, do suggest improvements for the Glucosio format in the referenced bug ticket. The poor choice in date format alone should be reason to change things up before they settle on anything.

**Comment by Flameeyes** [comment]
Given the unwillingness of glucosio project to talk with other open source projects rather than do things on their own, I'm not willing to spend time helping them out on this particular issue.
