### ISSUE TITLE
No dependencies defined

### ISSUE THREAD

**Issue by ex-nerd** [Flameeyes/glucometerutils#5]
Trying to run this but it seems to be missing `dateutils` and `pyscsi`.  The first was found via pip but it looks like the latter (maybe https://github.com/rosjat/python-scsi ? ) is not.  However, it would be nice to get these added to setup.py or at least documented in the README.

**Comment by ex-nerd** [comment]
It might also be worth mentioning that `pyscsi` is only compatible with Linux (would have saved me a bunch of searching to figure out why it wasn't working from OSX).

**Comment by Flameeyes** [comment]
The list of dependencies have been present in the README since almost the beginning, I think 5e3ca9c6c455346712f0f4822d45ab69e2ca05d7 made it more readable though.

And yes, python-scsi is only supported on Linux right now. I tried looking for something that would work on OSX, but it looks Apple does not let userspace send raw READ/WRITE commands to device. I'm not sure how the original software manages to talk to the Verio on OSX.

As for setup.py... I"m not very experienced with Python conditional dependencies, patches are really welcome :)

**Comment by finbarrocallaghan** [comment]
could potentially do something like [this](https://github.com/rosjat/python-scsi/blob/master/setup.py#L18) for the conditional dependency?

`if platform == 'darwin':`

[this](https://gist.github.com/finbarrocallaghan/990bab16b68c0f916f16411d6b7f422e) works for me, for dependencies, but has a number of undesirable tradeoffs

**Comment by lgp171188** [comment]
[Environment markers](https://www.python.org/dev/peps/pep-0426/#environment-markers) seem to be a clean way for solving this problem. We will require something like what is described in this [Stack Overflow answer](http://stackoverflow.com/a/32955538).

**Comment by Flameeyes** [comment]
This should be fixed with b8aa129750be9a6a56f14987401010edc8514b32.
